jobs:
  include:
  - stage: Build

    sudo: required
    services:
    - docker
    script: docker build -t vibioh/domaine:${TRAVIS_COMMIT} .
    after_success: |
      echo ${DOCKER_PASS} | docker login -u vibioh --password-stdin && \
      docker push vibioh/domaine:${TRAVIS_COMMIT}

  - stage: Publish

    sudo: required
    services:
    - docker
    script: |
      echo ${DOCKER_PASS} | docker login -u vibioh --password-stdin
      docker pull vibioh/domaine:${TRAVIS_COMMIT}
      docker tag vibioh/domaine:${TRAVIS_COMMIT} vibioh/domaine:latest
      docker push vibioh/domaine:latest

  - stage: Deploy

    script: skip
    deploy:
      provider: script
      skip_cleanup: true
      script: 'curl -H "Authorization: GitHub ${GITHUB_OAUTH_TOKEN}" -X POST https://dashboard-api.vibioh.fr/deploy/domaine/ --data-binary @docker-compose.yml'

stages:
  - Build
  - name: Deploy
    if: branch = master

notifications:
  email: false
