jobs:
  include:
  - stage: Build

    sudo: required
    services:
    - docker
    script: docker build --build-arg "APP_VERSION=${TRAVIS_COMMIT}" -t "vibioh/domaine:${TRAVIS_COMMIT}" .
    after_success:
    - echo "${DOCKER_PASS}" | docker login -u vibioh --password-stdin
    - docker push "vibioh/domaine:${TRAVIS_COMMIT}"

  - stage: Publish

    sudo: required
    services:
    - docker
    script:
    - echo "${DOCKER_PASS}" | docker login -u vibioh --password-stdin
    - docker pull "vibioh/domaine:${TRAVIS_COMMIT}"
    - docker tag "vibioh/domaine:${TRAVIS_COMMIT}" "vibioh/domaine:latest"
    - docker push "vibioh/domaine:latest"

  - stage: Deploy

    script: skip
    deploy:
      provider: script
      skip_cleanup: true
      script: bash script/deploy domaine "@docker-compose.yml"

stages:
  - Build
  - name: Publish
    if: branch = master && type = push
  - name: Deploy
    if: branch = master && type = push

notifications:
  email: false
