version: '2'

services:
  site:
    image: vibioh/domaine
    command:
    - -csp
    - "default-src 'self'; base-uri 'self'; script-src 'self' api.tiles.mapbox.com; style-src 'self' 'unsafe-inline' cdn.jsdelivr.net/npm/normalize.css@8.0.0/ use.fontawesome.com/releases/v5.2.0/css/ fonts.googleapis.com api.tiles.mapbox.com; img-src 'self' data: blob:; font-src 'self' fonts.gstatic.com use.fontawesome.com; connect-src 'self' *.mapbox.com; child-src 'self' blob:"
    - -headers
    - X-UA-Compatible:ie=edge~content-language:fr
    - -tracingName
    - domaine
    labels:
      traefik.frontend.passHostHeader: 'true'
      traefik.frontend.rule: 'Host: domaine-de-montdenis.fr, www.domaine-de-montdenis.fr'
      traefik.protocol: 'https'
      traefik.port: '1080'
      traefik.frontend.rateLimit.extractorFunc: 'client.ip'
      traefik.frontend.rateLimit.rateSet.first.period: '60s'
      traefik.frontend.rateLimit.rateSet.first.average: '100'
      traefik.frontend.rateLimit.rateSet.first.burst: '200'
    logging:
      driver: json-file
      options:
        max-size: '10m'
    restart: on-failure:5
    read_only: true
    cpu_shares: 128
    mem_limit: 67108864
    security_opt:
    - no-new-privileges

networks:
  default:
    external:
      name: traefik
