apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: domaine
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.47"
      sourceRef:
        kind: HelmRepository
        name: vibioh
        namespace: default
      interval: 120m
  install:
    skipCRDs: true
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: domaine
    image:
      repository: vibioh/domaine:202102280748 # {"$imagepolicy": "default:flux-domaine-web"}
    config:
      VIWS_LOGGER_JSON: "true"
    ingress:
      enabled: true
      hosts:
      - domaine-de.montdenis.fr
