apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: domaine
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.71"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: domaine
    image:
      name: vibioh/domaine
      tag: "202106051337" # {"$imagepolicy": "default:flux-domaine-web:tag"}
    config:
      VIWS_LOGGER_JSON: "true"
      VIWS_PROMETHEUS_GZIP: "false"
    ingress:
      enabled: true
      hosts:
      - domaine-de.montdenis.fr
    canary:
      enabled: true
      url: https://domaine-de.montdenis.fr
