apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: domaine
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.32"
      sourceRef:
        kind: HelmRepository
        name: vibioh
        namespace: flux-system
      interval: 120m
  values:
    nameOverride: domaine
    image:
      repository: vibioh/domaine:latest # {"$imagepolicy": "default:site-domaine"}
    config:
      VIWS_LOGGER_JSON: "true"
    ingress:
      enabled: true
      hosts:
      - domaine-de.montdenis.fr
